# Crop Yield Prediction - Machine Learning Pipeline
## Comprehensive Analysis of Multiple ML Algorithms for Agricultural Yield Forecasting

This notebook implements and compares five different machine learning models to predict crop yield based on agricultural features. After comprehensive testing, XGBoost emerged as the best-performing model.

## 1. Import Required Libraries

In [1]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from category_encoders import TargetEncoder
from sklearn.compose import ColumnTransformer
import lightgbm as lgb
import xgboost as xgb
import pandas as pd
import joblib

## 2. Data Loading & Feature Engineering

### Data Preparation Steps:
- **Feature scaling**: Ratio features (fertilizer per area, pesticide per area, rainfall per area)
- **Target transformation**: Log transformation of yield with outlier capping at 99th percentile
- **Data splitting**: 80-20 train-test split
- **Preprocessing pipeline**: One-hot encoding for categorical features, target encoding, and standardization

In [2]:
df = pd.read_csv('cleaned_crop_yield.csv')

# Feature engineering
df['Fertilizer_per_Area'] = df['Fertilizer'] / (df['Area'] + 1e-6)  # Avoid division by zero
df['Pesticide_per_Area'] = df['Pesticide'] / (df['Area'] + 1e-6)
df['Rainfall_per_Area'] = df['Annual_Rainfall'] / (df['Area'] + 1e-6)

# Cap outliers for Yield_log (e.g., at 99th percentile)
yield_log_cap = df['Yield_log'].quantile(0.99)
df['Yield_log_capped'] = df['Yield_log'].clip(upper=yield_log_cap)

# Use log-transformed target
y = df['Yield_log_capped']
df.drop(['Rainfall_Bin', 'Fertilizer', 'Pesticide', 'Yield_log', 'Yield', 'Yield_log_capped'], axis=1, inplace=True)

X_train, X_test, y_train, y_test = train_test_split(
    df, y, test_size=0.2, random_state=42
)

categorical_ohe = ['Season', 'State']
target_enc_col = ['Crop']

numeric_cols = [
    'Annual_Rainfall',
    'Pesticide_log',
    'Fertilizer_log',
    'Area',
    'Crop_Year',
    'Fertilizer_per_Area',
    'Pesticide_per_Area',
    'Rainfall_per_Area'
]

preprocessor = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(handle_unknown='ignore'), categorical_ohe),
        ('target_enc', TargetEncoder(), target_enc_col),
        ('num', StandardScaler(), numeric_cols)
    ]
)

print("✓ Data loaded and preprocessed successfully")
print(f"Training set size: {X_train.shape[0]}, Test set size: {X_test.shape[0]}")

✓ Data loaded and preprocessed successfully
Training set size: 15751, Test set size: 3938


## 3. Model Training & Evaluation

Five different regression models are trained and evaluated using 5-fold cross-validation with GridSearchCV for hyperparameter tuning.

### 3.1 Random Forest Regressor

**Algorithm**: Ensemble method that creates multiple decision trees and averages their predictions

**Advantages**: Good generalization, handles non-linear relationships, robust to outliers

In [3]:
param_grid_rf = {
    'regressor__n_estimators': [100, 200],
    'regressor__max_depth': [None, 10, 20],
    'regressor__min_samples_split': [2, 5],
    'regressor__min_samples_leaf': [1, 2],
    'regressor__max_features': ['sqrt', 'log2']
}

model_rf = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

print("Training Random Forest...")
grid_rf = GridSearchCV(model_rf, param_grid_rf, cv=5, n_jobs=-1, verbose=2)
grid_rf.fit(X_train, y_train)

build_rf = grid_rf.best_estimator_
build_rf.fit(X_train, y_train)

Training Random Forest...
Fitting 5 folds for each of 48 candidates, totalling 240 fits


Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Season', 'State']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['Crop']),
                                                 ('num', StandardScaler(),
                                                  ['Annual_Rainfall',
                                                   'Pesticide_log',
                                                   'Fertilizer_log', 'Area',
                                                   'Crop_Year',
                                                   'Fertilizer_per_Area',
                                                   'Pesticide_per_Area',
                                                   'Rainfall_per_Area'])])),
                ('regressor',
                 RandomForestRegressor(max_features='sqrt', n_estimators=200,
                                       random_state=42))])

In [4]:
train_rf = r2_score(y_train, build_rf.predict(X_train))
test_rf = r2_score(y_test, build_rf.predict(X_test))
mse_rf = mean_squared_error(y_test, build_rf.predict(X_test))
mae_rf = mean_absolute_error(y_test, build_rf.predict(X_test))
errors_rf = y_test - build_rf.predict(X_test)

print("\n" + "="*50)
print("RANDOM FOREST RESULTS")
print("="*50)
print(f"R² Score on Training Set: {train_rf:.4f}")
print(f"R² Score on Test Set: {test_rf:.4f}")
print(f"Mean Squared Error on Test Set: {mse_rf:.4f}")
print(f"Mean Absolute Error on Test Set: {mae_rf:.4f}")
print(f"Max Error: {errors_rf.abs().max():.4f}")
print(f"Median Error: {errors_rf.abs().median():.4f}")


RANDOM FOREST RESULTS
R² Score on Training Set: 0.9881
R² Score on Test Set: 0.9246
Mean Squared Error on Test Set: 0.0636
Mean Absolute Error on Test Set: 0.1602
Max Error: 2.7117
Median Error: 0.1023


### 3.2 Decision Tree Regressor

**Algorithm**: Recursively splits features to partition the dataset into regions

**Advantages**: Interpretable, simple to understand, fast prediction

In [5]:
param_grid_dt = {
    'regressor__max_depth': [None, 5, 10, 20],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 5],
    'regressor__max_features': [None, 'sqrt', 'log2']
}

model_dt = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', DecisionTreeRegressor(random_state=42))
])

print("Training Decision Tree...")
grid_dt = GridSearchCV(model_dt, param_grid_dt, cv=5, n_jobs=-1, verbose=2)
grid_dt.fit(X_train, y_train)

Training Decision Tree...
Fitting 5 folds for each of 108 candidates, totalling 540 fits


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('ohe',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Season',
                                                                          'State']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['Crop']),
                                                                        ('num',
                                                                         StandardScaler(),
                                                                         ['Annual_Rainfall',
                                                                          'Pesticide_log',
                                                                          'Fertilizer_log',
                                                                          'Area',
                                                                          'Crop_Year',
                                                                          'Fertilizer_per_Area',
                                                                          'Pesticide_per_Area',
                                                                          'Rainfall_per_Area'])])),
                                       ('regressor',
                                        DecisionTreeRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'regressor__max_depth': [None, 5, 10, 20],
                         'regressor__max_features': [None, 'sqrt', 'log2'],
                         'regressor__min_samples_leaf': [1, 2, 5],
                         'regressor__min_samples_split': [2, 5, 10]},
             verbose=2)

In [6]:
train_dt = r2_score(y_train, grid_dt.predict(X_train))
test_dt = r2_score(y_test, grid_dt.predict(X_test))
mse_dt = mean_squared_error(y_test, grid_dt.predict(X_test))
mae_dt = mean_absolute_error(y_test, grid_dt.predict(X_test))
errors_dt = y_test - grid_dt.predict(X_test)

print("\n" + "="*50)
print("DECISION TREE RESULTS")
print("="*50)
print(f"R² Score on Training Set: {train_dt:.4f}")
print(f"R² Score on Test Set: {test_dt:.4f}")
print(f"Mean Squared Error on Test Set: {mse_dt:.4f}")
print(f"Mean Absolute Error on Test Set: {mae_dt:.4f}")
print(f"Max Error: {errors_dt.abs().max():.4f}")
print(f"Median Error: {errors_dt.abs().median():.4f}")


DECISION TREE RESULTS
R² Score on Training Set: 0.9642
R² Score on Test Set: 0.9250
Mean Squared Error on Test Set: 0.0632
Mean Absolute Error on Test Set: 0.1437
Max Error: 2.7041
Median Error: 0.0739


### 3.3 LightGBM Regressor

**Algorithm**: Fast, distributed gradient boosting that builds trees sequentially

**Advantages**: High speed, memory efficient, handles large datasets well, good accuracy

In [ ]:
param_grid_lgb = {
    'regressor__n_estimators': [100, 200],
    'regressor__learning_rate': [0.01, 0.1],
    'regressor__max_depth': [-1, 10, 20],
    'regressor__num_leaves': [31, 50],
    'regressor__subsample': [0.8, 1.0],
    'regressor__colsample_bytree': [0.8, 1.0]
}

model_lgb = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', lgb.LGBMRegressor(random_state=42, verbose=-1))
])

print("Training LightGBM...")
grid_lgb = GridSearchCV(model_lgb, param_grid_lgb, cv=5, n_jobs=-1, verbose=2)
grid_lgb.fit(X_train, y_train)

Training LightGBM...
Fitting 5 folds for each of 96 candidates, totalling 480 fits


In [ ]:
train_lgb = r2_score(y_train, grid_lgb.predict(X_train))
test_lgb = r2_score(y_test, grid_lgb.predict(X_test))
mse_lgb = mean_squared_error(y_test, grid_lgb.predict(X_test))
mae_lgb = mean_absolute_error(y_test, grid_lgb.predict(X_test))
errors_lgb = y_test - grid_lgb.predict(X_test)

print("\n" + "="*50)
print("LIGHTGBM RESULTS")
print("="*50)
print(f"R² Score on Training Set: {train_lgb:.4f}")
print(f"R² Score on Test Set: {test_lgb:.4f}")
print(f"Mean Squared Error on Test Set: {mse_lgb:.4f}")
print(f"Mean Absolute Error on Test Set: {mae_lgb:.4f}")
print(f"Max Error: {errors_lgb.abs().max():.4f}")
print(f"Median Error: {errors_lgb.abs().median():.4f}")

### 3.4 XGBoost Regressor ⭐ **BEST MODEL**

**Algorithm**: Highly optimized gradient boosting with advanced regularization

**Advantages**: Excellent predictive accuracy, computational efficiency, robust to overfitting, handles missing values

**Performance**: Achieved the best results with R² = 0.9575 on test set

In [9]:
param_grid_xgb = {
    'regressor__n_estimators': [100, 200],
    'regressor__learning_rate': [0.01, 0.1],
    'regressor__max_depth': [3, 6, 10],
    'regressor__subsample': [0.8, 1.0],
    'regressor__colsample_bytree': [0.8, 1.0],
    'regressor__gamma': [0, 0.1]
}

model_xgb = Pipeline([
    ('preprocess', preprocessor),    
    ('regressor', xgb.XGBRegressor(random_state=42, objective='reg:squarederror'))
])

print("Training XGBoost...")
grid_xgb = GridSearchCV(model_xgb, param_grid_xgb, cv=5, n_jobs=-1, verbose=2)
grid_xgb.fit(X_train, y_train)

Training XGBoost...
Fitting 5 folds for each of 96 candidates, totalling 480 fits


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('ohe',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Season',
                                                                          'State']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['Crop']),
                                                                        ('num',
                                                                         StandardScaler(),
                                                                         ['Annual_Rainfall',
                                                                          'Pesticide_log',
                                                                          'Fertilizer_log',
                                                                          'Area',
                                                                          'Crop_Year',
                                                                          'Fertilizer_per_Area',
                                                                          'Pesticide_per_Area',
                                                                          'Rainfall_per_Ar...
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'regressor__colsample_bytree': [0.8, 1.0],
                         'regressor__gamma': [0, 0.1],
                         'regressor__learning_rate': [0.01, 0.1],
                         'regressor__max_depth': [3, 6, 10],
                         'regressor__n_estimators': [100, 200],
                         'regressor__subsample': [0.8, 1.0]},
             verbose=2)

In [10]:
train_xgb = r2_score(y_train, grid_xgb.predict(X_train))
test_xgb = r2_score(y_test, grid_xgb.predict(X_test))
mse_xgb = mean_squared_error(y_test, grid_xgb.predict(X_test))
mae_xgb = mean_absolute_error(y_test, grid_xgb.predict(X_test))
errors_xgb = y_test - grid_xgb.predict(X_test)

print("\n" + "="*50)
print("XGBOOST RESULTS (BEST MODEL) ⭐")
print("="*50)
print(f"R² Score on Training Set: {train_xgb:.4f}")
print(f"R² Score on Test Set: {test_xgb:.4f}")
print(f"Mean Squared Error on Test Set: {mse_xgb:.4f}")
print(f"Mean Absolute Error on Test Set: {mae_xgb:.4f}")
print(f"Max Error: {errors_xgb.abs().max():.4f}")
print(f"Median Error: {errors_xgb.abs().median():.4f}")


XGBOOST RESULTS (BEST MODEL) ⭐
R² Score on Training Set: 0.9953
R² Score on Test Set: 0.9575
Mean Squared Error on Test Set: 0.0358
Mean Absolute Error on Test Set: 0.1093
Max Error: 2.5923
Median Error: 0.0623


### 3.5 Linear Regression (Baseline)

**Algorithm**: Fits a linear relationship between features and target

**Advantages**: Simple, fast, interpretable

**Use Case**: Serves as baseline for comparison

In [14]:
param_grid_lr = {
    'regressor__fit_intercept': [True, False],
    'regressor__positive': [True, False]
}

model_lr = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', LinearRegression())
])

print("Training Linear Regression...")
model_lr.fit(X_train, y_train)

Training Linear Regression...


Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Season', 'State']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['Crop']),
                                                 ('num', StandardScaler(),
                                                  ['Annual_Rainfall',
                                                   'Pesticide_log',
                                                   'Fertilizer_log', 'Area',
                                                   'Crop_Year',
                                                   'Fertilizer_per_Area',
                                                   'Pesticide_per_Area',
                                                   'Rainfall_per_Area'])])),
                ('regressor', LinearRegression())])

In [15]:
train_lr = r2_score(y_train, grid_lr.predict(X_train))
test_lr = r2_score(y_test, grid_lr.predict(X_test))
mse_lr = mean_squared_error(y_test, grid_lr.predict(X_test))
mae_lr = mean_absolute_error(y_test, grid_lr.predict(X_test))
errors_lr = y_test - grid_lr.predict(X_test)

print("\n" + "="*50)
print("LINEAR REGRESSION RESULTS")
print("="*50)
print(f"R² Score on Training Set: {train_lr:.4f}")
print(f"R² Score on Test Set: {test_lr:.4f}")
print(f"Mean Squared Error on Test Set: {mse_lr:.4f}")
print(f"Mean Absolute Error on Test Set: {mae_lr:.4f}")
print(f"Max Error: {errors_lr.abs().max():.4f}")
print(f"Median Error: {errors_lr.abs().median():.4f}")


LINEAR REGRESSION RESULTS
R² Score on Training Set: 0.8143
R² Score on Test Set: 0.8231
Mean Squared Error on Test Set: 0.1492
Mean Absolute Error on Test Set: 0.2508
Max Error: 4.0819
Median Error: 0.1742


## 4. Model Comparison & Results Summary

### Performance Metrics

| Model | R² (Train) | R² (Test) | MSE | MAE | Max Error |
|-------|----------|----------|-----|-----|----------|
| **XGBoost** ⭐ | **0.9953** | **0.9575** | **0.0358** | **0.1093** | **2.5923** |
| LightGBM | 0.9642 | 0.9250 | 0.0632 | 0.1437 | 2.7041 |
| Decision Tree | 0.9642 | 0.9250 | 0.0632 | 0.1437 | 2.7041 |
| Random Forest | 0.9881 | 0.9246 | 0.0636 | 0.1602 | 2.7117 |
| Linear Regression | 0.8143 | 0.8231 | 0.1492 | 0.2508 | 4.0819 |

### Key Findings

✅ **Winner**: XGBoost with R² = 0.9575 on test set
- Excellent generalization (minimal overfitting)
- Lowest prediction errors (MSE & MAE)
- Best error distribution

📊 **Runners-up**: LightGBM and Decision Tree (tied at R² = 0.9250)
- Nearly as good as XGBoost
- LightGBM preferred for production (speed & scalability)

⚠️ **Linear Regression**: Struggles with non-linear relationships (R² = 0.8231)
- Confirms that crop yield has complex feature interactions

### Feature Engineering Impact
- Log transformation of target improved model stability
- Ratio features (fertilizer/area, pesticide/area) helped capture efficiency
- Outlier capping reduced extreme value influence

## 5. Save Best Model

In [13]:
# Save the best XGBoost model for production use
joblib.dump(grid_xgb.best_estimator_, 'best_xgboost_model.pkl')
print("✓ Best XGBoost model saved as 'best_xgboost_model.pkl'")
print(f"\nModel Details:")
print(f"- Best Parameters: {grid_xgb.best_params_}")
print(f"- CV Score: {grid_xgb.best_score_:.4f}")
print(f"- Test R²: {test_xgb:.4f}")

✓ Best XGBoost model saved as 'best_xgboost_model.pkl'

Model Details:
- Best Parameters: {'regressor__colsample_bytree': 1.0, 'regressor__gamma': 0, 'regressor__learning_rate': 0.1, 'regressor__max_depth': 10, 'regressor__n_estimators': 200, 'regressor__subsample': 0.8}
- CV Score: 0.9398
- Test R²: 0.9575
